export default {
  SHOW_NAVBAR: "SHOW_NAVBAR",
  SET_ERROR_MESSAGE: "SET_ERROR_MESSAGE",
  RESET_ERROR_MESSAGE: "RESET_ERROR_MESSAGE",
  SET_SUCCESS_MESSAGE: "SET_SUCCESS_MESSAGE",
  RESET_SUCCESS_MESSAGE: "RESET_SUCCESS_MESSAGE",
  SHOW_LOGIN_FORM: "SHOW_LOGIN_FORM",
  HIDE_LOGIN_FORM: "HIDE_LOGIN_FORM",
  SHOW_REGISTRATION_FORM: "SHOW_REGISTRATION_FORM",
  HIDE_REGISTRATION_FORM: "HIDE_REGISTRATION_FORM"
};